sonar.projectKey=sqlutionsfatec_analysis-backend
sonar.organization=sqlutionsfatec

sonar.projectName=Analysis Backend
sonar.projectVersion=1.0

sonar.sources=django
sonar.tests=django/api/tests
sonar.test.inclusions=django/api/tests/**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/.venv/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=django/coverage.xml
sonar.sourceEncoding=UTF-8
