# Generated by Django 5.2.14 on 2026-09-09 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_arquivo', models.CharField(help_text='Ex: pdf, docx, png', max_length=50)),
                ('nome', models.CharField(help_text='Nome do documento', max_length=255)),
                ('setor', models.CharField(help_text='Setor responsável pelo documento', max_length=100)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Atualizado automaticamente no salvamento')),
                ('nivel', models.CharField(help_text='Nível de acesso ou sigilo do documento', max_length=50)),
                ('data', models.FileField(help_text='Arquivo do documento', upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'etiqueta',
            },
        ),
        migrations.CreateModel(
            name='EtiquetaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_relacao', to='api.documento')),
                ('id_etiqueta', models.ForeignKey(db_column='id_etiqueta', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacao', to='api.etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta do Documento',
                'verbose_name_plural': 'Etiquetas do Documento',
                'db_table': 'etiqueta_documento',
                'unique_together': {('id_documento', 'id_etiqueta')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='etiquetas',
            field=models.ManyToManyField(related_name='documentos', through='api.EtiquetaDocumento', to='api.etiqueta'),
        ),
    ]
