# Generated by Django 5.2.14 on 2026-09-21 23:28

import api.models.documento_chunk
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentochunk'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='documentochunk',
            name='embedding',
            field=api.models.documento_chunk.VectorField(blank=True, help_text='Embedding vetorial do chunk com 768 dimensões', null=True),
        ),
    ]
