name: Backend - Integration Tests and Sonar

on:
  push:
    branches:
      - main
      - develop-1

  pull_request:
    branches:
      - main
      - develop-1
    types:
      - opened
      - synchronize
      - reopened

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Build and run integration tests
        run: |
          docker compose \
            -f deploy/docker-compose.test.yml \
            up \
            --build \
            --abort-on-container-exit \
            --exit-code-from backend-test

      - name: Show generated test files
        if: always()
        run: |
          echo "Generated files:"
          ls -la django/ || true

      - name: Stop integration environment
        if: always()
        run: |
          docker compose \
            -f deploy/docker-compose.test.yml \
            down -v \
            --remove-orphans

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
